export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const CREATE_PROJECTS_SUCCESS = 'CREATE_PROJECTS_SUCCESS';
export const UPDATE_TASK_STATUS_SUCCESS = 'UPDATE_TASK_STATUS_SUCCESS';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_MEMBERS_SUCCESS = 'CREATE_MEMBERS_SUCCESS';
