export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const LOAD_MEMBERS_SUCCESS = 'LOAD_MEMBERS_SUCCESS';
export const UPDATE_MEMBERS_SUCCESS = 'UPDATE_MEMBERS_SUCCESS';
export const CREATE_PROJECTS_SUCCESS = 'CREATE_PROJECTS_SUCCESS';
export const CREATE_MEMBERS_SUCCESS = 'CREATE_MEMBERS_SUCCESS';
